spring:
  application:
    name: external-task-example
  datasource:
    url: jdbc:h2:mem:orqueio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

orqueio:
  bpm:
    rest-api:
      enabled: true
      basic-auth-enabled: false
    database:
      schema-update: true
    job-execution:
      core-pool-size: 3
    authorization:
      enabled: false
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    deployment-resource-pattern: classpath*:bpmn/*.bpmn
  base-url: http://localhost:8080/engine-rest

logging:
  level:
    root: INFO
    io.orqueio: DEBUG
    io.orqueio.externaltask: DEBUG
